
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqcgwetqfjfzmsdmkzje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxY2d3ZXRxZmpmem1zZG1remplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzAwNzQsImV4cCI6MjA1NzUwNjA3NH0.U92oVlD2mx1T03OZwgQ1vidJ24ukOyLD8zj4rllEMcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Helper function to get the current user's ID (if logged in)
export const getCurrentUserId = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error("Error getting current user ID:", error);
      return null;
    }
    
    return data.session?.user?.id || null;
  } catch (err) {
    console.error("Exception getting current user ID:", err);
    return null;
  }
};

// Helper function to get user data (including session)
export const getUserData = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error("Error getting user data:", error);
      return null;
    }
    
    return data.session?.user || null;
  } catch (err) {
    console.error("Exception getting user data:", err);
    return null;
  }
};
