// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxbzsueqfojduxwxzuiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4YnpzdWVxZm9qZHV4d3h6dWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzk0OTYsImV4cCI6MjA2OTExNTQ5Nn0.SlbY-XuziYtQFkAVf-T7IzH84dc-a_wgaGBMnjtnbmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});